version: '3.3'
services:
  web:
    build: 
      context: ./alendre_dasneuner
      dockerfile: Dockerfile
    container_name: alendre_dasneuner
    volumes:
      - ./alendre_dasneuner:/var/www/html/
    ports:
      - 8002:80
  
  db:
    container_name: alendre_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alendre_dasneuner
      MYSQL_USER: dev#@_dasneuner#@
      MYSQL_PASSWORD: dev#@_dasneuner#@324940#@
    ports:
        - 6033:3306

Deployment start
Repository git@github.com:AlendreLopes/alendre_dasneuner.git
Checking project directory is empty
Project directory is empty
Cloning code repository
Repository cloned
Looking for composer.lock file
composer.lock file was not found
Looking for composer.json file
composer.json file was not found
Deployment end